### ISSUE TITLE
Small query on the output format

### ISSUE THREAD

**Issue by jeremytanjianle** [SDM-TIB/falcon2.0#11]
Hi

Would like to raise 2 (points / questions):

(1) the `doctype` should be `doc` or `_doc` in the `Elastic` submodule?
The source code by default reads `doc`, but the `Elasticdump` seems to add `_doc` by default. 
It's a small point, but thought it should be raised, in case this affects adding new docs. 

(2)
How to interpret the result?
Trying Falcon on random questions provide the following results. How do we interpret the integers that come after the list of links? Thank you. 
```
>>>    process_text_E_R('Who is Michelle Obama?',rules)
>>>    process_text_E_R('Where is Gracht?',rules)
0
['Who is Michelle Obama?', [], [['<http://www.wikidata.org/entity/Q13133>', 'Michelle obama']], 0, 0, 0, 0]
1
['Where is Gracht?', [], [['<http://www.wikidata.org/entity/Q896611>', 'Gracht']], 0, 0, 0, 0]
```

**Comment by AhmadSakor** [comment]
Hi

1) you can use it as it's in the dump now. This is not a problem
2) these integers represents P and R for entity and relation linking. They are zeros now because the evaluation flag is False
