### ISSUE TITLE
Some kind of entity sorting error

### ISSUE THREAD

**Issue by jeremytanjianle** [SDM-TIB/falcon2.0#12]
Hi,

I've encountered errors when querying entities of single digits e.g. Earth is Q2. 

The error is logged below. 
```
    for entity in sorted(raw , key=lambda x: (-x[3],-x[2],int(x[1][x[1].rfind("/")+2:-1])))[:k]:
ValueError: invalid literal for int() with base 10: ''
```

I've managed to fix this with the following indexing where the -1 in the slicing is removed.
```
    for entity in sorted(raw , key=lambda x: (-x[3],-x[2],int(x[1][x[1].rfind("/")+2:])))[:k]:
```
I believe this -1 truncates the sorted id by a digit unintentionally at the back. For example: 
```
1. Q2' -> ''
2. 'Q123' -> 12
```
Hoping to hear if this is a correct change please or if it can affect the overall package. Thanks 😄

**Comment by AhmadSakor** [comment]
Hi @vinitrinh 
thanks for your interest and comment.
We are going to release a new version soon where all of these issues are solved.
