### ISSUE TITLE
Handling `'s` in entity indexing

### ISSUE THREAD

**Issue by jeremytanjianle** [SDM-TIB/falcon2.0#13]
Had difficulty parsing the following:
```
print( process_text_E_R("Hong Kong's",rules) )
```
The resulting error is:
```
ValueError: 'Kong' is not in list
```
This seems to come from the mismatch where `["Hong", "Kong's"].index("Kong")`.  

I've tried a fix by adding new rule in the various entity cleaning portions. Hoping to hear if this would make sense with the rules and parsing. Thank you 😸 
```
            for ent in entities: 
                ent=ent.replace("?","")
                ent=ent.replace(".","")
                ent=ent.replace("!","")
                ent=ent.replace("\\","")
                ent=ent.replace("#","")
                ent=ent.replace("'s","") < added new rule in line 439
                if token.text in ent:
```

**Comment by jeremytanjianle** [comment]
A similar but more challenging question is:
```
print( process_text_E_R("What countries are in Asia-Pacific?",rules) )
```
It seems that the `"-"` can really mess up the code snippets referenced above.
---
Sorry, just running the following causes the error:
```
print( process_text_E_R("Asia-Pacific?",rules) )
```

**Comment by AhmadSakor** [comment]
Hi @vinitrinh 
thanks for your interest and comment.
We are going to release a new version soon where all of these issues are solved.
