### ISSUE TITLE
FileNotFound Error 

### ISSUE THREAD

**Issue by nimo21** [SDM-TIB/falcon2.0#7]
Hi @AhmadSakor,
When I set up this code, I got an error called _FileNotFoundError: [Errno 2] No such file or directory: 'datasets/results/test_api/falcon_lcquad2.csv_' in evaluateFalconAPI.py file. The same error came when running evaluateFalconAPI_entities.py file (falcon_simple_test.csv not found). Pls, be kind enough to provide me with these CSV files or give any solution to solve these errors.

**Comment by AhmadSakor** [comment]
Hi @nimo21 
These files are the result of running Falcon 2.0 over the benchmark datasets.
You are getting this error because the directory (results/test_api) doesn't exist.
You just need to create these two sub-directories(results, and test_api) inside datasets folder, Or you can simply change the path of the files to datasets folder directly

**Comment by AhmadSakor** [comment]
I changed the paths of the files. So just pull the new version of the scripts, then everything should work fine.

**Comment by AhmadSakor** [comment]
I also uploaded the CSV files.
please find them here
https://github.com/SDM-TIB/falcon2.0/tree/master/datasets/results/test_api

**Comment by nimo21** [comment]
Hi @AhmadSakor,
Thank you for your support. I want to use this tool for another language other than English. Is it possible if I used the data set related to that language?

**Comment by AhmadSakor** [comment]
Hi @nimo21 

Thanks for your interest in our work.
Yes, it's possible. You need to replace the approach English background knowledge with a background knowledge in the language that you are targeting.
Also, a few modifications to the rules may be required according to the linguistics of the language you are targeting.
We are working now on supporting more language for our approach.
Feel free to let us know what is the language you are targeting, and we will let you know once Falcon 2.0 supports it.

**Comment by nimo21** [comment]
I'm targeting language is Sinhala. 
Your quick response is highly appreciated.

**Comment by nimo21** [comment]
I'm targeting for the Sinhala language.  
Your quick response is highly appreciative.

**Comment by nimo21** [comment]
Your contribution is highly appreciated regarding this matter. My targeting language is Sinhala.

**Comment by AhmadSakor** [comment]
Hi @nimo21 

Supporting the Sinhala language is not in our soon to do list.
We will search for compatible components for the Sinhala language and let you know once we are able to support it.
In the meanwhile don't hesitate to contact us via email. We can arrange a Skype call and discuss how we can contribute with you.
